# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3485b279f32e9767274937ef5f0680a45ad9a380c8d11d37db47acab195a2f3c2b2cd52e0f5d20919133065dd38c45cd0556e7ecd87372684bfc18b24414fea3

test:s
  secret_key_base: e2028111c395d3272062f3a5eec03f38cce87addce073257f117b4b94c4456eea502d46641efe4bfd45ecad96d08c611c19edcb2d988c2eaa91f61507c61a5dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
